# Generated by Django 4.1.2 on 2023-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='password',
            field=models.CharField(default='undefined', max_length=200),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.CharField(default='undefined', max_length=200),
        ),
    ]
