# Generated by Django 4.1.2 on 2023-01-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_password_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='password',
        ),
    ]
